<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="https://getbootstrap.com/docs/4.1/assets/img/favicons/favicon.ico">

  <title>Dashboard Template for Bootstrap</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/4.1/examples/dashboard/">

  <link href="/css/bootstrap.css" rel="stylesheet">

  <link href="/css/dashboard.css" rel="stylesheet">
</head>
<body>

<#include ${userType}-"/side_and_navbarGuest">
<#include ${userType}-"/content.ftlh">

<#include "/footer.ftlh">
</div>
</div>


<script src="/js/bootstrap.js"></script>
<script src="/js/feather.js"></script>
<script>
  feather.replace()
</script>


</body>
</html>