<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">
</head>
<body>
Dear Admin,<br><br>
I would like to kindly ask for vacation from ${vacation.dateFrom} to ${vacation.dateTo}.<br><br>
${vacation.deputy} will cover for me on that day.<br><br>
Please count this day against my annual leave balance.<br><br>
Thank you for understanding.<br><br>
Best Regards,<br>
${employee.firstName} ${employee.secondName}
</body>
</html>